### ISSUE TITLE
Incorporating edge weights

### ISSUE THREAD

**Issue by Filco306** [mberr/torch-ppr#22]
Hello, 

Thank you for this great repository; it is a great, handy package that performs very well! I was wondering however; is it possible to incorporate edge weights into the personalized pagerank method? 

Best
Filip

**Comment by Filco306** [comment]
Oh, I found now that one can pass `adj` where rows sum to 1; I assume those are edge weights, if this is not true please correct me, otherwise, I will close this now :)

**Comment by cthoyt** [comment]
@Filco306 It would be great if you could contribute a small example about what you're doing so we could include it in the documentation. Thanks for your interest!

**Comment by Filco306** [comment]
Sure! I'll file a PR :)

**Comment by cthoyt** [comment]
that's great! The best place to put a new example would be inside the docstring for the PPR function itself all the way at the bottom, just before this: https://github.com/mberr/torch-ppr/blob/a5de68835cd4dd879b386f0f28bfe6297feb6262/src/torch_ppr/api.py#L138
